source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.0'

gem 'rails', '~> 6.0.3'
gem 'mysql2', '>= 0.4.4'
gem 'puma', '~> 4.1'
gem 'webpacker', '~> 4.0'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.7'
gem 'bootsnap', '>= 1.4.2', require: false

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  gem 'webdrivers'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# カスタムgem
gem 'simple_form'
gem 'devise'
gem 'devise_token_auth'
gem 'kaminari'
gem 'enumerize'
gem 'pry-rails'
gem 'faker'
gem 'rack-cors'
gem 'carrierwave'
gem 'annotate'
gem 'react-rails'
gem 'stripe'
gem 'dotenv-rails'
gem 'rails-i18n', '~> 6.0'
gem 'devise-i18n'
gem 'redcarpet'
gem 'coderay'
